version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - "80:80"
    working_dir: /var/www/html
    user: root
    command:
      - /bin/bash
      - -c 
      - |
        chmod 777 /var/www/html/run_application.sh
        /var/www/html/run_application.sh development 